---
# Try to write results to stdout and display
# ansible-playbook example1.yml --ask-pass
#
- hosts: all
  tasks:
  - shell: 'df -h'
    register: psk

- set_fact: 
    psk={{ psk.stdout }}

  - debug: var=psk
