---
# This playbook prints a simple hello world message
- name: Executes ucommand passed in extra vars
  hosts: all

  shell:
    cmd: "{{ ucommand }}""
  - debug: msg="Command executed: {{ ucommand }}"
